# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' test function for FastAD
#'
#' @examples
#' test_forward()
#' @export
test_forward <- function() {
    .Call(`_fastadr_test_forward`)
}

